export const fullSizeLayout = [
  [
    { key_id: 1, colspan: "1", key_name: "ESC" },
    { key_id: 999, colspan: "1", key_name: "" },
    { key_id: 2, colspan: "1", key_name: "F1" },
    { key_id: 3, colspan: "1", key_name: "F2" },
    { key_id: 4, colspan: "1", key_name: "F3" },
    { key_id: 5, colspan: "1", key_name: "F4" },
    { key_id: 999, colspan: "1", key_name: "" },
    { key_id: 6, colspan: "1", key_name: "F5" },
    { key_id: 7, colspan: "1", key_name: "F6" },
    { key_id: 8, colspan: "1", key_name: "F7" },
    { key_id: 9, colspan: "1", key_name: "F8" },
    { key_id: 999, colspan: "1", key_name: "" },
    { key_id: 10, colspan: "1", key_name: "F9" },
    { key_id: 11, colspan: "1", key_name: "F10" },
    { key_id: 12, colspan: "1", key_name: "F11" },
    { key_id: 13, colspan: "1", key_name: "F12" },
    { key_id: 999, colspan: "1", key_name: "" },
    { key_id: 1000, colspan: "1", key_name: "PRTSC" },
    { key_id: 1001, colspan: "1", key_name: "SCRLK" },
    { key_id: 1002, colspan: "1", key_name: "PAUSE" },
  ],
  [
    { key_id: 14, colspan: "1", key_name: "`" },
    { key_id: 15, colspan: "1", key_name: "1" },
    { key_id: 16, colspan: "1", key_name: "2" },
    { key_id: 17, colspan: "1", key_name: "3" },
    { key_id: 18, colspan: "1", key_name: "4" },
    { key_id: 19, colspan: "1", key_name: "5" },
    { key_id: 20, colspan: "1", key_name: "6" },
    { key_id: 21, colspan: "1", key_name: "7" },
    { key_id: 22, colspan: "1", key_name: "8" },
    { key_id: 23, colspan: "1", key_name: "9" },
    { key_id: 24, colspan: "1", key_name: "0" },
    { key_id: 25, colspan: "1", key_name: "-" },
    { key_id: 26, colspan: "1", key_name: "=" },
    { key_id: 27, colspan: "1", key_name: "←" },
    { key_id: 999, colspan: "1", key_name: "" },
    { key_id: 1003, colspan: "1", key_name: "INS" },
    { key_id: 1004, colspan: "1", key_name: "HOME" },
    { key_id: 1005, colspan: "1", key_name: "PG UP" },
    { key_id: 999, colspan: "1", key_name: "" },
    { key_id: 2000, colspan: "1", key_name: "NUMLK" },
    { key_id: 2001, colspan: "1", key_name: "/" },
    { key_id: 2002, colspan: "1", key_name: "*" },
    { key_id: 2003, colspan: "1", key_name: "-" },
  ],
  [
    { key_id: 28, colspan: "1", key_name: "TAB" },
    { key_id: 29, colspan: "1", key_name: "Q" },
    { key_id: 30, colspan: "1", key_name: "W" },
    { key_id: 31, colspan: "1", key_name: "E" },
    { key_id: 32, colspan: "1", key_name: "R" },
    { key_id: 33, colspan: "1", key_name: "T" },
    { key_id: 34, colspan: "1", key_name: "Y" },
    { key_id: 35, colspan: "1", key_name: "U" },
    { key_id: 36, colspan: "1", key_name: "I" },
    { key_id: 37, colspan: "1", key_name: "O" },
    { key_id: 38, colspan: "1", key_name: "P" },
    { key_id: 39, colspan: "1", key_name: "[" },
    { key_id: 40, colspan: "1", key_name: "]" },
    { key_id: 41, colspan: "1", key_name: "\\" },
    { key_id: 999, colspan: "1", key_name: "" },
    { key_id: 1006, colspan: "1", key_name: "DEL" },
    { key_id: 1007, colspan: "1", key_name: "END" },
    { key_id: 1008, colspan: "1", key_name: "PG DN" },
    { key_id: 999, colspan: "1", key_name: "" },
    { key_id: 2004, colspan: "1", key_name: "7" },
    { key_id: 2005, colspan: "1", key_name: "8" },
    { key_id: 2006, colspan: "1", key_name: "9" },
    { key_id: 2007, colspan: "1", key_name: "+" },
  ],
  [
    { key_id: 42, colspan: "1", key_name: "CAPS" },
    { key_id: 43, colspan: "1", key_name: "A" },
    { key_id: 44, colspan: "1", key_name: "S" },
    { key_id: 45, colspan: "1", key_name: "D" },
    { key_id: 46, colspan: "1", key_name: "F" },
    { key_id: 47, colspan: "1", key_name: "G" },
    { key_id: 48, colspan: "1", key_name: "H" },
    { key_id: 49, colspan: "1", key_name: "J" },
    { key_id: 50, colspan: "1", key_name: "K" },
    { key_id: 51, colspan: "1", key_name: "L" },
    { key_id: 52, colspan: "1", key_name: ";" },
    { key_id: 53, colspan: "1", key_name: "'" },
    { key_id: 54, colspan: "1", key_name: "ENTER" },
    { key_id: 999, colspan: "1", key_name: "" },
    { key_id: 999, colspan: "1", key_name: "" },
    { key_id: 999, colspan: "1", key_name: "" },
    { key_id: 2004, colspan: "1", key_name: "4" },
    { key_id: 2005, colspan: "1", key_name: "5" },
    { key_id: 2006, colspan: "1", key_name: "6" },
  ],
  [
    { key_id: 55, colspan: "1", key_name: "Shift" },
    { key_id: 56, colspan: "1", key_name: "Z" },
    { key_id: 57, colspan: "1", key_name: "X" },
    { key_id: 58, colspan: "1", key_name: "C" },
    { key_id: 59, colspan: "1", key_name: "V" },
    { key_id: 60, colspan: "1", key_name: "B" },
    { key_id: 61, colspan: "1", key_name: "N" },
    { key_id: 62, colspan: "1", key_name: "M" },
    { key_id: 63, colspan: "1", key_name: "," },
    { key_id: 64, colspan: "1", key_name: "." },
    { key_id: 65, colspan: "1", key_name: "/" },
    { key_id: 66, colspan: "1", key_name: "SHIFT" },
    { key_id: 999, colspan: "1", key_name: "" },
    { key_id: 1009, colspan: "1", key_name: "↑" },
    { key_id: 999, colspan: "1", key_name: "" },
    { key_id: 2007, colspan: "1", key_name: "1" },
    { key_id: 2008, colspan: "1", key_name: "2" },
    { key_id: 2009, colspan: "1", key_name: "3" },
    { key_id: 2010, colspan: "1", key_name: "ENTER" },
  ],
  [
    { key_id: 67, colspan: "1", key_name: "CTRL" },
    { key_id: 68, colspan: "1", key_name: "WIN" },
    { key_id: 69, colspan: "1", key_name: "ALT" },
    { key_id: 70, colspan: "1", key_name: "SPACE" },
    { key_id: 71, colspan: "1", key_name: "ALT" },
    { key_id: 72, colspan: "1", key_name: "FN" },
    { key_id: 73, colspan: "1", key_name: "MENU" },
    { key_id: 74, colspan: "1", key_name: "CTRL" },
    { key_id: 999, colspan: "1", key_name: "" },
    { key_id: 1010, colspan: "1", key_name: "←" },
    { key_id: 1011, colspan: "1", key_name: "↓" },
    { key_id: 1012, colspan: "1", key_name: "→" },
    { key_id: 999, colspan: "1", key_name: "" },
    { key_id: 2011, colspan: "1", key_name: "0" },
    { key_id: 2012, colspan: "1", key_name: "." },
  ],
];
