export const fullSizeLayout = [
  [
    { key_id: 1, size: "w-10", key_name: "ESC" },
    { key_id: 999, size: "w-10", key_name: "" },
    { key_id: 2, size: "w-10", key_name: "F1" },
    { key_id: 3, size: "w-10", key_name: "F2" },
    { key_id: 4, size: "w-10", key_name: "F3" },
    { key_id: 5, size: "w-10", key_name: "F4" },
    { key_id: 999, size: "w-10", key_name: "" },
    { key_id: 6, size: "w-10", key_name: "F5" },
    { key_id: 7, size: "w-10", key_name: "F6" },
    { key_id: 8, size: "w-10", key_name: "F7" },
    { key_id: 9, size: "w-10", key_name: "F8" },
    { key_id: 999, size: "w-10", key_name: "" },
    { key_id: 10, size: "w-10", key_name: "F9" },
    { key_id: 11, size: "w-10", key_name: "F10" },
    { key_id: 12, size: "w-10", key_name: "F11" },
    { key_id: 13, size: "w-10", key_name: "F12" },
    { key_id: 999, size: "w-10", key_name: "" },
    { key_id: 1000, size: "w-10", key_name: "PRTSC" },
    { key_id: 1001, size: "w-10", key_name: "SCRLK" },
    { key_id: 1002, size: "w-10", key_name: "PAUSE" },
  ],
  [
    { key_id: 14, size: "w-10", key_name: "`" },
    { key_id: 15, size: "w-10", key_name: "1" },
    { key_id: 16, size: "w-10", key_name: "2" },
    { key_id: 17, size: "w-10", key_name: "3" },
    { key_id: 18, size: "w-10", key_name: "4" },
    { key_id: 19, size: "w-10", key_name: "5" },
    { key_id: 20, size: "w-10", key_name: "6" },
    { key_id: 21, size: "w-10", key_name: "7" },
    { key_id: 22, size: "w-10", key_name: "8" },
    { key_id: 23, size: "w-10", key_name: "9" },
    { key_id: 24, size: "w-10", key_name: "0" },
    { key_id: 25, size: "w-10", key_name: "-" },
    { key_id: 26, size: "w-10", key_name: "=" },
    { key_id: 27, size: "w-10", key_name: "BACKSPACE" },
    { key_id: 999, size: "w-10", key_name: "" },
    { key_id: 1003, size: "w-10", key_name: "INS" },
    { key_id: 1004, size: "w-10", key_name: "HOME" },
    { key_id: 1005, size: "w-10", key_name: "PG UP" },
    { key_id: 999, size: "w-10", key_name: "" },
    { key_id: 2000, size: "w-10", key_name: "NUMLK" },
    { key_id: 2001, size: "w-10", key_name: "/" },
    { key_id: 2002, size: "w-10", key_name: "*" },
    { key_id: 2003, size: "w-10", key_name: "-" },
  ],
  [
    { key_id: 28, size: "w-10", key_name: "TAB" },
    { key_id: 29, size: "w-10", key_name: "Q" },
    { key_id: 30, size: "w-10", key_name: "W" },
    { key_id: 31, size: "w-10", key_name: "E" },
    { key_id: 32, size: "w-10", key_name: "R" },
    { key_id: 33, size: "w-10", key_name: "T" },
    { key_id: 34, size: "w-10", key_name: "Y" },
    { key_id: 35, size: "w-10", key_name: "U" },
    { key_id: 36, size: "w-10", key_name: "I" },
    { key_id: 37, size: "w-10", key_name: "O" },
    { key_id: 38, size: "w-10", key_name: "P" },
    { key_id: 39, size: "w-10", key_name: "[" },
    { key_id: 40, size: "w-10", key_name: "]" },
    { key_id: 41, size: "w-10", key_name: "\\" },
    { key_id: 999, size: "w-10", key_name: "" },
    { key_id: 1006, size: "w-10", key_name: "DEL" },
    { key_id: 1007, size: "w-10", key_name: "END" },
    { key_id: 1008, size: "w-10", key_name: "PG DN" },
    { key_id: 999, size: "w-10", key_name: "" },
    { key_id: 2004, size: "w-10", key_name: "7" },
    { key_id: 2005, size: "w-10", key_name: "8" },
    { key_id: 2006, size: "w-10", key_name: "9" },
    { key_id: 2007, size: "w-10", key_name: "+" },
  ],
  [
    { key_id: 42, size: "w-10", key_name: "CAPS" },
    { key_id: 43, size: "w-10", key_name: "A" },
    { key_id: 44, size: "w-10", key_name: "S" },
    { key_id: 45, size: "w-10", key_name: "D" },
    { key_id: 46, size: "w-10", key_name: "F" },
    { key_id: 47, size: "w-10", key_name: "G" },
    { key_id: 48, size: "w-10", key_name: "H" },
    { key_id: 49, size: "w-10", key_name: "J" },
    { key_id: 50, size: "w-10", key_name: "K" },
    { key_id: 51, size: "w-10", key_name: "L" },
    { key_id: 52, size: "w-10", key_name: ";" },
    { key_id: 53, size: "w-10", key_name: "'" },
    { key_id: 54, size: "w-10", key_name: "ENTER" },
    { key_id: 999, size: "w-10", key_name: "" },
    { key_id: 999, size: "w-10", key_name: "" },
    { key_id: 999, size: "w-10", key_name: "" },
    { key_id: 2004, size: "w-10", key_name: "4" },
    { key_id: 2005, size: "w-10", key_name: "5" },
    { key_id: 2006, size: "w-10", key_name: "6" },
  ],
  [
    { key_id: 55, size: "w-10", key_name: "Shift" },
    { key_id: 56, size: "w-10", key_name: "Z" },
    { key_id: 57, size: "w-10", key_name: "X" },
    { key_id: 58, size: "w-10", key_name: "C" },
    { key_id: 59, size: "w-10", key_name: "V" },
    { key_id: 60, size: "w-10", key_name: "B" },
    { key_id: 61, size: "w-10", key_name: "N" },
    { key_id: 62, size: "w-10", key_name: "M" },
    { key_id: 63, size: "w-10", key_name: "," },
    { key_id: 64, size: "w-10", key_name: "." },
    { key_id: 65, size: "w-10", key_name: "/" },
    { key_id: 66, size: "w-10", key_name: "SHIFT" },
    { key_id: 999, size: "w-10", key_name: "" },
    { key_id: 1009, size: "w-10", key_name: "↑" },
    { key_id: 999, size: "w-10", key_name: "" },
    { key_id: 2007, size: "w-10", key_name: "1" },
    { key_id: 2008, size: "w-10", key_name: "2" },
    { key_id: 2009, size: "w-10", key_name: "3" },
    { key_id: 2010, size: "w-10", key_name: "ENTER" },
  ],
  [
    { key_id: 67, size: "w-10", key_name: "LEFT CTRL" },
    { key_id: 68, size: "w-10", key_name: "WIN" },
    { key_id: 69, size: "w-10", key_name: "LEFT ALT" },
    { key_id: 70, size: "w-10", key_name: "SPACE" },
    { key_id: 71, size: "w-10", key_name: "RIGHT ALT" },
    { key_id: 72, size: "w-10", key_name: "FN" },
    { key_id: 73, size: "w-10", key_name: "MENU" },
    { key_id: 74, size: "w-10", key_name: "RIGHT CTRL" },
    { key_id: 999, size: "w-10", key_name: "" },
    { key_id: 1010, size: "w-10", key_name: "←" },
    { key_id: 1011, size: "w-10", key_name: "↓" },
    { key_id: 1012, size: "w-10", key_name: "→" },
    { key_id: 999, size: "w-10", key_name: "" },
    { key_id: 2011, size: "w-10", key_name: "0" },
    { key_id: 2012, size: "w-10", key_name: "." },
  ],
];
