export const mac_os_75 = [
  // 14 keys
  { label: "ESC", width: "min-w-10", row: "1", font_size: "text-[9px]" },
  { label: "1", width: "min-w-10", row: "1" },
  { label: "2", width: "min-w-10", row: "1" },
  { label: "3", width: "min-w-10", row: "1" },
  { label: "4", width: "min-w-10", row: "1" },
  { label: "5", width: "min-w-10", row: "1" },
  { label: "6", width: "min-w-10", row: "1" },
  { label: "7", width: "min-w-10", row: "1" },
  { label: "8", width: "min-w-10", row: "1" },
  { label: "9", width: "min-w-10", row: "1" },
  { label: "0", width: "min-w-10", row: "1" },
  { label: "-", width: "min-w-10", row: "1" },
  { label: "=", width: "min-w-10", row: "1" },
  {
    label: "DELETE",
    width: "min-w-10",
    row: "1",
    flexGrow: true,
    font_size: "text-[9px]",
  },

  // 14 keys
  { label: "TAB", width: "min-w-12", row: "2", font_size: "text-[9px]" },
  { label: "Q", width: "min-w-10", row: "2" },
  { label: "W", width: "min-w-10", row: "2" },
  { label: "E", width: "min-w-10", row: "2" },
  { label: "R", width: "min-w-10", row: "2" },
  { label: "T", width: "min-w-10", row: "2" },
  { label: "Y", width: "min-w-10", row: "2" },
  { label: "U", width: "min-w-10", row: "2" },
  { label: "I", width: "min-w-10", row: "2" },
  { label: "O", width: "min-w-10", row: "2" },
  { label: "P", width: "min-w-10", row: "2" },
  { label: "[", width: "min-w-10", row: "2" },
  { label: "]", width: "min-w-10", row: "2" },
  { label: "|", width: "min-w-10", row: "2", flexGrow: true },

  // 13 keys
  { label: "CAPS", width: "min-w-14", row: "3", font_size: "text-[9px]" },
  { label: "A", width: "min-w-10", row: "3" },
  { label: "S", width: "min-w-10", row: "3" },
  { label: "D", width: "min-w-10", row: "3" },
  { label: "F", width: "min-w-10", row: "3" },
  { label: "G", width: "min-w-10", row: "3" },
  { label: "H", width: "min-w-10", row: "3" },
  { label: "J", width: "min-w-10", row: "3" },
  { label: "K", width: "min-w-10", row: "3" },
  { label: "L", width: "min-w-10", row: "3" },
  { label: ";", width: "min-w-10", row: "3" },
  { label: "'", width: "min-w-10", row: "3" },
  {
    label: "RETURN",
    width: "full",
    row: "3",
    flexGrow: true,
    font_size: "text-[9px]",
  },

  // 14 keys
  { label: "SHIFT", width: "min-w-16", row: "4", font_size: "text-[9px]" },
  { label: "Z", width: "min-w-10", row: "4" },
  { label: "X", width: "min-w-10", row: "4" },
  { label: "C", width: "min-w-10", row: "4" },
  { label: "V", width: "min-w-10", row: "4" },
  { label: "B", width: "min-w-10", row: "4" },
  { label: "N", width: "min-w-10", row: "4" },
  { label: "M", width: "min-w-10", row: "4" },
  { label: ",", width: "min-w-10", row: "4" },
  { label: ".", width: "min-w-10", row: "4" },
  { label: "/", width: "min-w-10", row: "4" },
  { label: "SHIFT", width: "min-w-10", row: "4", font_size: "text-[9px]" },
  { label: "↑", width: "min-w-10", row: "4" },
  { label: "CTRL", width: "min-w-10", row: "4", font_size: "text-[9px]" },

  // 10 keys
  { label: "FN", width: "min-w-10", row: "5", font_size: "text-[9px]" },
  { label: "CTRL", width: "min-w-10", row: "5", font_size: "text-[9px]" },
  { label: "OPT", width: "min-w-10", row: "5", font_size: "text-[9px]" },
  { label: "CMD", width: "min-w-10", row: "5", font_size: "text-[9px]" },
  { label: "", width: "min-w-10", row: "5", flexGrow: true },
  { label: "CMD", width: "min-w-10", row: "5", font_size: "text-[9px]" },
  { label: "OPT", width: "min-w-10", row: "5", font_size: "text-[9px]" },
  { label: "←", width: "min-w-10", row: "5" },
  { label: "↓", width: "min-w-10", row: "5" },
  { label: "→", width: "min-w-10", row: "5" },
];
