// The backend will provide the physical properties such as key_id, and label, and color
// while the frontend is responsible for visual properties
// this is joined by they key_id

import { KeyProps } from "../../../util/types.ts";

export const win_65: KeyProps[] = [
  // 14 keys
  {
    key_id: "esc",
    label: "ESC",
    width: "min-w-10",
    row: "1",
    font_size: "text-[9px]",
  },
  { key_id: "1", label: "1", width: "min-w-10", row: "1" },
  { key_id: "2", label: "2", width: "min-w-10", row: "1" },
  { key_id: "3", label: "3", width: "min-w-10", row: "1" },
  { key_id: "4", label: "4", width: "min-w-10", row: "1" },
  { key_id: "5", label: "5", width: "min-w-10", row: "1" },
  { key_id: "6", label: "6", width: "min-w-10", row: "1" },
  { key_id: "7", label: "7", width: "min-w-10", row: "1" },
  { key_id: "8", label: "8", width: "min-w-10", row: "1" },
  { key_id: "9", label: "9", width: "min-w-10", row: "1" },
  { key_id: "0", label: "0", width: "min-w-10", row: "1" },
  { key_id: "dash", label: "-", width: "min-w-10", row: "1" },
  { key_id: "equal", label: "=", width: "min-w-10", row: "1" },
  {
    key_id: "backspace",
    label: "BACKSPACE",
    width: "min-w-10",
    row: "1",
    flexGrow: true,
    font_size: "text-[9px]",
  },

  // 14 keys
  {
    key_id: "tab",
    label: "TAB",
    width: "min-w-12",
    row: "2",
    font_size: "text-[9px]",
  },
  { key_id: "q", label: "Q", width: "min-w-10", row: "2" },
  { key_id: "w", label: "W", width: "min-w-10", row: "2" },
  { key_id: "e", label: "E", width: "min-w-10", row: "2" },
  { key_id: "r", label: "R", width: "min-w-10", row: "2" },
  { key_id: "t", label: "T", width: "min-w-10", row: "2" },
  { key_id: "y", label: "Y", width: "min-w-10", row: "2" },
  { key_id: "u", label: "U", width: "min-w-10", row: "2" },
  { key_id: "i", label: "I", width: "min-w-10", row: "2" },
  { key_id: "o", label: "O", width: "min-w-10", row: "2" },
  { key_id: "p", label: "P", width: "min-w-10", row: "2" },
  { key_id: "left_square_bracket", label: "[", width: "min-w-10", row: "2" },
  { key_id: "right_square_bracket", label: "]", width: "min-w-10", row: "2" },
  {
    key_id: "back_slash",
    label: "\\",
    width: "min-w-10",
    row: "2",
    flexGrow: true,
  },

  // 13 keys
  {
    key_id: "caps_lock",
    label: "CAPS",
    width: "min-w-14",
    row: "3",
    font_size: "text-[9px]",
  },
  { key_id: "a", label: "A", width: "min-w-10", row: "3" },
  { key_id: "s", label: "S", width: "min-w-10", row: "3" },
  { key_id: "d", label: "D", width: "min-w-10", row: "3" },
  { key_id: "f", label: "F", width: "min-w-10", row: "3" },
  { key_id: "g", label: "G", width: "min-w-10", row: "3" },
  { key_id: "h", label: "H", width: "min-w-10", row: "3" },
  { key_id: "j", label: "J", width: "min-w-10", row: "3" },
  { key_id: "k", label: "K", width: "min-w-10", row: "3" },
  { key_id: "l", label: "L", width: "min-w-10", row: "3" },
  { key_id: "semi_colon", label: ";", width: "min-w-10", row: "3" },
  { key_id: "single_quote", label: "'", width: "min-w-10", row: "3" },
  {
    key_id: "enter",
    label: "RETURN",
    width: "full",
    row: "3",
    flexGrow: true,
    font_size: "text-[9px]",
  },

  // 14 keys
  {
    key_id: "shift_left",
    label: "SHIFT",
    width: "min-w-16",
    row: "4",
    font_size: "text-[9px]",
  },
  { key_id: "z", label: "Z", width: "min-w-10", row: "4" },
  { key_id: "x", label: "X", width: "min-w-10", row: "4" },
  { key_id: "c", label: "C", width: "min-w-10", row: "4" },
  { key_id: "v", label: "V", width: "min-w-10", row: "4" },
  { key_id: "b", label: "B", width: "min-w-10", row: "4" },
  { key_id: "n", label: "N", width: "min-w-10", row: "4" },
  { key_id: "m", label: "M", width: "min-w-10", row: "4" },
  { key_id: "comma", label: ",", width: "min-w-10", row: "4" },
  { key_id: "period", label: ".", width: "min-w-10", row: "4" },
  { key_id: "forward_slash", label: "/", width: "min-w-10", row: "4" },
  {
    key_id: "shift_right",
    label: "SHIFT",
    width: "min-w-10",
    row: "4",
    font_size: "text-[9px]",
  },
  { key_id: "up_arrow", label: "↑", width: "min-w-10", row: "4" },
  {
    key_id: "ctrl_right",
    label: "CTRL",
    width: "min-w-10",
    row: "4",
    font_size: "text-[9px]",
  },

  // 10 keys
  {
    key_id: "fn",
    label: "FN",
    width: "min-w-10",
    row: "5",
    font_size: "text-[9px]",
  },
  {
    key_id: "ctrl_left",
    label: "CTRL",
    width: "min-w-10",
    row: "5",
    font_size: "text-[9px]",
  },
  {
    key_id: "win",
    label: "WIN",
    width: "min-w-10",
    row: "5",
    font_size: "text-[9px]",
  },
  {
    key_id: "alt_left",
    label: "ALT",
    width: "min-w-10",
    row: "5",
    font_size: "text-[9px]",
  },
  { key_id: "space", label: "", width: "min-w-10", row: "5", flexGrow: true },
  {
    key_id: "alt_right",
    label: "ALT",
    width: "min-w-10",
    row: "5",
    font_size: "text-[9px]",
  },
  {
    key_id: "menu",
    label: "MENU",
    width: "min-w-10",
    row: "5",
    font_size: "text-[9px]",
  },
  { key_id: "left_arrow", label: "←", width: "min-w-10", row: "5" },
  { key_id: "down_arrow", label: "↓", width: "min-w-10", row: "5" },
  { key_id: "right_arrow", label: "→", width: "min-w-10", row: "5" },
];
