export const fullSizeLayout = [
  [
    { key_id: 1, col_span: "1", key_name: "ESC" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 2, col_span: "1", key_name: "F1" },
    { key_id: 3, col_span: "1", key_name: "F2" },
    { key_id: 4, col_span: "1", key_name: "F3" },
    { key_id: 5, col_span: "1", key_name: "F4" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 6, col_span: "1", key_name: "F5" },
    { key_id: 7, col_span: "1", key_name: "F6" },
    { key_id: 8, col_span: "1", key_name: "F7" },
    { key_id: 9, col_span: "1", key_name: "F8" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 10, col_span: "1", key_name: "F9" },
    { key_id: 11, col_span: "1", key_name: "F10" },
    { key_id: 12, col_span: "1", key_name: "F11" },
    { key_id: 13, col_span: "1", key_name: "F12" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 1000, col_span: "1", key_name: "PRTSC" },
    { key_id: 1001, col_span: "1", key_name: "SCRLK" },
    { key_id: 1002, col_span: "1", key_name: "PAUSE" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 999, col_span: "1", key_name: "" },
  ],
  [
    { key_id: 14, col_span: "1", key_name: "`" },
    { key_id: 15, col_span: "1", key_name: "1" },
    { key_id: 16, col_span: "1", key_name: "2" },
    { key_id: 17, col_span: "1", key_name: "3" },
    { key_id: 18, col_span: "1", key_name: "4" },
    { key_id: 19, col_span: "1", key_name: "5" },
    { key_id: 20, col_span: "1", key_name: "6" },
    { key_id: 21, col_span: "1", key_name: "7" },
    { key_id: 22, col_span: "1", key_name: "8" },
    { key_id: 23, col_span: "1", key_name: "9" },
    { key_id: 24, col_span: "1", key_name: "0" },
    { key_id: 25, col_span: "1", key_name: "-" },
    { key_id: 26, col_span: "1", key_name: "=" },
    { key_id: 27, col_span: "2", key_name: "←" },
    { key_id: 999, col_span: "1", key_name: "" }, // temp
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 1003, col_span: "1", key_name: "INS" },
    { key_id: 1004, col_span: "1", key_name: "HOME" },
    { key_id: 1005, col_span: "1", key_name: "UP" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 2000, col_span: "1", key_name: "NMLK" },
    { key_id: 2001, col_span: "1", key_name: "/" },
    { key_id: 2002, col_span: "1", key_name: "*" },
    { key_id: 2003, col_span: "1", key_name: "-" },
  ],
  [
    { key_id: 28, col_span: "1", key_name: "TAB" },
    { key_id: 29, col_span: "1", key_name: "Q" },
    { key_id: 30, col_span: "1", key_name: "W" },
    { key_id: 31, col_span: "1", key_name: "E" },
    { key_id: 32, col_span: "1", key_name: "R" },
    { key_id: 33, col_span: "1", key_name: "T" },
    { key_id: 34, col_span: "1", key_name: "Y" },
    { key_id: 35, col_span: "1", key_name: "U" },
    { key_id: 36, col_span: "1", key_name: "I" },
    { key_id: 37, col_span: "1", key_name: "O" },
    { key_id: 38, col_span: "1", key_name: "P" },
    { key_id: 39, col_span: "1", key_name: "[" },
    { key_id: 40, col_span: "1", key_name: "]" },
    { key_id: 41, col_span: "1", key_name: "\\" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 999, col_span: "1", key_name: "" }, // temp
    { key_id: 999, col_span: "1", key_name: "" }, // temp
    { key_id: 1006, col_span: "1", key_name: "DEL" },
    { key_id: 1007, col_span: "1", key_name: "END" },
    { key_id: 1008, col_span: "1", key_name: "DN" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 2004, col_span: "1", key_name: "7" },
    { key_id: 2005, col_span: "1", key_name: "8" },
    { key_id: 2006, col_span: "1", key_name: "9" },
    { key_id: 2007, col_span: "1", row_span: "2", key_name: "+" },
  ],
  [
    { key_id: 42, col_span: "1", key_name: "CAPS" },
    { key_id: 43, col_span: "1", key_name: "A" },
    { key_id: 44, col_span: "1", key_name: "S" },
    { key_id: 45, col_span: "1", key_name: "D" },
    { key_id: 46, col_span: "1", key_name: "F" },
    { key_id: 47, col_span: "1", key_name: "G" },
    { key_id: 48, col_span: "1", key_name: "H" },
    { key_id: 49, col_span: "1", key_name: "J" },
    { key_id: 50, col_span: "1", key_name: "K" },
    { key_id: 51, col_span: "1", key_name: "L" },
    { key_id: 52, col_span: "1", key_name: ";" },
    { key_id: 53, col_span: "1", key_name: "'" },
    { key_id: 54, col_span: "1", key_name: "ENTER" },
    { key_id: 999, col_span: "1", key_name: "" }, // temp
    { key_id: 999, col_span: "1", key_name: "" }, // temp
    { key_id: 999, col_span: "1", key_name: "" }, // temp
    { key_id: 999, col_span: "1", key_name: "" }, // temp
    { key_id: 999, col_span: "1", key_name: "" }, // temp
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 2004, col_span: "1", key_name: "4" },
    { key_id: 2005, col_span: "1", key_name: "5" },
    { key_id: 2006, col_span: "1", key_name: "6" },
  ],
  [
    { key_id: 55, col_span: "1", key_name: "SHIFT" },
    { key_id: 56, col_span: "1", key_name: "Z" },
    { key_id: 57, col_span: "1", key_name: "X" },
    { key_id: 58, col_span: "1", key_name: "C" },
    { key_id: 59, col_span: "1", key_name: "V" },
    { key_id: 60, col_span: "1", key_name: "B" },
    { key_id: 61, col_span: "1", key_name: "N" },
    { key_id: 62, col_span: "1", key_name: "M" },
    { key_id: 63, col_span: "1", key_name: "," },
    { key_id: 64, col_span: "1", key_name: "." },
    { key_id: 65, col_span: "1", key_name: "/" },
    { key_id: 66, col_span: "1", key_name: "SHIFT" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 1009, col_span: "1", key_name: "↑" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 2007, col_span: "1", key_name: "1" },
    { key_id: 2008, col_span: "1", key_name: "2" },
    { key_id: 2009, col_span: "1", key_name: "3" },
    { key_id: 2010, col_span: "1", row_span: "2", key_name: "ENTER" },
  ],
  [
    { key_id: 67, col_span: "1", key_name: "CTRL" },
    { key_id: 68, col_span: "1", key_name: "WIN" },
    { key_id: 69, col_span: "1", key_name: "ALT" },
    { key_id: 70, col_span: "5", key_name: "SPACE" },
    { key_id: 71, col_span: "1", key_name: "ALT" },
    { key_id: 72, col_span: "1", key_name: "FN" },
    { key_id: 73, col_span: "1", key_name: "MENU" },
    { key_id: 74, col_span: "1", key_name: "CTRL" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 1010, col_span: "1", key_name: "←" },
    { key_id: 1011, col_span: "1", key_name: "↓" },
    { key_id: 1012, col_span: "1", key_name: "→" },
    { key_id: 999, col_span: "1", key_name: "" },
    { key_id: 2011, col_span: "1", key_name: "0" },
    { key_id: 2012, col_span: "1", key_name: "." },
  ],
];
