export const keys2 = [
  { label: "`", width: "full", row: "1" },
  { label: "1", width: "full", row: "1" },
  { label: "2", width: "full", row: "1" },
  { label: "3", width: "full", row: "1" },
  { label: "4", width: "full", row: "1" },
  { label: "5", width: "full", row: "1" },
  { label: "6", width: "full", row: "1" },
  { label: "7", width: "full", row: "1" },
  { label: "8", width: "full", row: "1" },
  { label: "9", width: "full", row: "1" },
  { label: "0", width: "full", row: "1" },
  { label: "-", width: "full", row: "1" },
  { label: "=", width: "full", row: "1", flexGrow: true },
  { label: "delete", width: "full", row: "1", flexGrow: true },
  { label: "tab", width: "full", row: "2", flexGrow: true },
  { label: "Q", width: "full", row: "2" },
  { label: "W", width: "full", row: "2" },
  { label: "E", width: "full", row: "2" },
  { label: "R", width: "full", row: "2" },
  { label: "T", width: "full", row: "2" },
  { label: "Y", width: "full", row: "2" },
  { label: "U", width: "full", row: "2" },
  { label: "I", width: "full", row: "2" },
  { label: "O", width: "full", row: "2" },
  { label: "P", width: "full", row: "2" },
  { label: "[", width: "12", row: "2" },
  { label: "]", width: "12", row: "2" },
  { label: "|", width: "full", row: "2", flexGrow: true },
  { label: "caps", width: "full", row: "3", flexGrow: true },
  { label: "A", width: "full", row: "3" },
  { label: "S", width: "full", row: "3" },
  { label: "D", width: "full", row: "3" },
  { label: "F", width: "full", row: "3" },
  { label: "G", width: "full", row: "3" },
  { label: "H", width: "full", row: "3" },
  { label: "J", width: "full", row: "3" },
  { label: "K", width: "full", row: "3" },
  { label: "L", width: "full", row: "3" },
  { label: ";", width: "full", row: "3" },
  { label: "'", width: "full", row: "3" },
  { label: "return", width: "full", row: "3", flexGrow: true },
  { label: "shift", width: "20", row: "4", flexGrow: true },
  { label: "Z", width: "full", row: "4" },
  { label: "X", width: "full", row: "4" },
  { label: "C", width: "full", row: "4" },
  { label: "V", width: "full", row: "4" },
  { label: "B", width: "full", row: "4" },
  { label: "N", width: "full", row: "4" },
  { label: "M", width: "full", row: "4" },
  { label: ",", width: "full", row: "4" },
  { label: ".", width: "full", row: "4" },
  { label: "/", width: "full", row: "4" },
  { label: "shift", width: "full", row: "4", flexGrow: true },
  { label: "▲", width: "full", row: "4" },
  { label: "", width: "full", row: "4" },
  { label: "fn", width: "full", row: "5" },
  { label: "ctrl", width: "full", row: "5" },
  { label: "opt", width: "full", row: "5" },
  { label: "cmd", width: "full", row: "5" },
  { label: "", width: "full", row: "5", flexGrow: true },
  { label: "cmd", width: "full", row: "5" },
  { label: "opt", width: "full", row: "5" },
  { label: "◄", width: "full", row: "5" },
  { label: "▼", width: "full", row: "5" },
  { label: "►", width: "full", row: "5" },
];
