export const keys2 = [
  { label: "esc", width: "40", row: "1"},
  { label: "1", width: "40", row: "1" },
  { label: "2", width: "40", row: "1" },
  { label: "3", width: "40", row: "1" },
  { label: "4", width: "40", row: "1" },
  { label: "5", width: "40", row: "1" },
  { label: "6", width: "40", row: "1" },
  { label: "7", width: "40", row: "1" },
  { label: "8", width: "40", row: "1" },
  { label: "9", width: "40", row: "1" },
  { label: "0", width: "40", row: "1" },
  { label: "-", width: "40", row: "1" },
  { label: "=", width: "40", row: "1" },
  { label: "delete", width: "80", row: "1"},

  { label: "tab", width: "123", row: "2" },
  { label: "Q", width: "40", row: "2" },
  { label: "W", width: "40", row: "2" },
  { label: "E", width: "40", row: "2" },
  { label: "R", width: "40", row: "2" },
  { label: "T", width: "40", row: "2" },
  { label: "Y", width: "40", row: "2" },
  { label: "U", width: "40", row: "2" },
  { label: "I", width: "40", row: "2" },
  { label: "O", width: "40", row: "2" },
  { label: "P", width: "40", row: "2" },
  { label: "[", width: "40", row: "2" },
  { label: "]", width: "40", row: "2" },
  { label: "|", width: "40", row: "2" },
  //
  // { label: "caps", width: "14", row: "3", flexGrow: true },
  // { label: "A", width: "10", row: "3" },
  // { label: "S", width: "10", row: "3" },
  // { label: "D", width: "10", row: "3" },
  // { label: "F", width: "10", row: "3" },
  // { label: "G", width: "10", row: "3" },
  // { label: "H", width: "10", row: "3" },
  // { label: "J", width: "10", row: "3" },
  // { label: "K", width: "10", row: "3" },
  // { label: "L", width: "10", row: "3" },
  // { label: ";", width: "10", row: "3" },
  // { label: "'", width: "10", row: "3" },
  // { label: "return", width: "10", row: "3", flexGrow: true },
  //
  // { label: "shift    ", width: "10", row: "4", flexGrow: true },
  // { label: "Z", width: "10", row: "4" },
  // { label: "X", width: "10", row: "4" },
  // { label: "C", width: "10", row: "4" },
  // { label: "V", width: "10", row: "4" },
  // { label: "B", width: "10", row: "4" },
  // { label: "N", width: "10", row: "4" },
  // { label: "M", width: "10", row: "4" },
  // { label: ",", width: "10", row: "4" },
  // { label: ".", width: "10", row: "4" },
  // { label: "/", width: "10", row: "4" },
  // { label: "shift    ", width: "10", row: "4", flexGrow: true},
  // { label: "▲", width: "10", row: "4" },
  // { label: "", width: "10", row: "4" },
  //
  // { label: "fn", width: "10", row: "5" },
  // { label: "ctrl", width: "10", row: "5" },
  // { label: "opt", width: "10", row: "5" },
  // { label: "cmd", width: "10", row: "5" },
  // { label: "", width: "10", row: "5", flexGrow: true },
  // { label: "cmd", width: "10", row: "5" },
  // { label: "opt", width: "10", row: "5" },
  // { label: "◄", width: "10", row: "5" },
  // { label: "▼", width: "10", row: "5" },
  // { label: "►", width: "10", row: "5" },
];
